global:
 scrape_interval: 15s
 evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:8000'

  - job_name: 'postgres'
    static_configs:
      - targets:
          - 'localhost:9187' 

  - job_name: 'flower'
    static_configs:
      - targets: 
          - 'localhost:5555'

  - job_name: 'celey'
    static_configs:
      - targets: 
          - 'localhost:9808'